name: Install Playwright Dependencies
description: Install playwright dependencies and cache browser binaries.
runs:
  using: "composite"
  steps:
    - name: Get playwright version
      id: playwright-info
      run: |
        version=$(
          npm ls @playwright/test --json \
          | jq --raw-output '.dependencies["@playwright/test"].version'
        )
        echo "version=$version" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache playwright browser binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-info.outputs.version }}
    - name: Install playwright browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
      shell: bash
    - name: Install playwright system dependencies
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      run: npx playwright install-deps
      shell: bash
