name: CI
on:
  pull_request:
    paths:
      - .github/**
      - packages/core/**
      - "!packages/core/.gitignore"
      - "!packages/core/README.md"
    branches:
      - main
    paths:
      - .github/**
      - packages/core/**
      - "!packages/core/.gitignore"
      - "!packages/core/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Build package
        run: bun --cwd packages/core build
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Check code style
        run: bun --cwd packages/core eslint
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Check code style
        run: bun --cwd packages/core prettier
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run tests
        run: bun --cwd packages/core test
